name = "idea"
main = ".open-next/worker.js"
compatibility_date = "2026-08-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "idea"
database_id = "f3fba48e-4718-4cf2-8f07-2f0ce9a1a541"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "49ca242930ac476fad471ba8dce7426a"

[vars]
ZAI_API_KEY = "hn_bb36e4976b3f37054e52aa2e6a669fa4"
ZAI_BASE_URL = "https://acdc.space-z.ai/api/v1"
